<!DOCTYPE html>
<html lang="en">
<head>
  <title>Pesona NTT</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="shortcut icon"  href="image/icon.png">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <style>.color-change-3x {
	-webkit-animation: color-change-3x 4s linear infinite alternate both;
	        animation: color-change-3x 4s linear infinite alternate both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-11-22 6:18:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-3x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-3x {
  0% {
    background: #0087ff;
  }
  50% {
    background: #05ecc6;
  }
  100% {
    background:  #01df3b;
  }
}
@keyframes color-change-3x {
  0% {
    background: #0087ff;
  }
  50% {
    background: #05ecc6;
  }
  100% {
    background: #01df3b;
  }
}

.zoom {
  transition: transform .2s; /* Animation */
  margin: 0 auto;
}
.zoom:hover {
  transform: scale(1.1); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}

/* ----------------------------------------------
 * Generated by Animista on 2020-12-1 6:8:12
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-right-1
 * ----------------------------------------
 */
@-webkit-keyframes tilt-in-right-1 {
  0% {
    -webkit-transform: rotateX(-30deg) translateX(300px) skewX(30deg);
            transform: rotateX(-30deg) translateX(300px) skewX(30deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg) translateX(0) skewX(0deg);
            transform: rotateX(0deg) translateX(0) skewX(0deg);
    opacity: 1;
  }
}
@keyframes tilt-in-right-1 {
  0% {
    -webkit-transform: rotateX(-30deg) translateX(300px) skewX(30deg);
            transform: rotateX(-30deg) translateX(300px) skewX(30deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateX(0deg) translateX(0) skewX(0deg);
            transform: rotateX(0deg) translateX(0) skewX(0deg);
    opacity: 1;
  }
}

.tilt-in-right-1 {
	-webkit-animation: tilt-in-right-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: tilt-in-right-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

</style>
</head>
<body class="color-change-3x">
<?php
  session_start();
  error_reporting(0);
?>
<!-- watsapp -->
<a style="position: fixed; background-image: url(image/icon-wa.png); bottom: 0; width: 70px; height: 50px; margin: 20px; right: 0; background-repeat: round; z-index: 2;" 
href="https://api.whatsapp.com/send?phone=6282197818711&amp;text=From+Pesona NTT%3A%0D%0ADear+Super+Admin+Pesona NTT.+Saya+ingin+berkonsultasi.%0D%0ABerikut+ini+adalah+identitas+saya%3A" 
target="_blank" title="Hubungi kami via Whatsapp"></a>

<?php
//Koneksi ke database
include 'superadmin/konektor.php';
include 'superadmin/enkripsivariabel.php';
?> 

<div class="container shadow p-4 mb-4 bg-white">

<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="image/benner1.jpg" alt="Los Angeles" width="100%" height="100%">  
    </div>
    <div class="carousel-item">
      <img src="image/benner2.jpg" alt="Chicago" width="100%" height="100%">
    </div>
    <div class="carousel-item">
      <img src="image/benner1.jpg" alt="New York" width="100%" height="100%">
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top" style="background-image: url(image/navbar2.jpg);background-size: cover;>
<img src="image/icon2.png" width="55px" height="35px"> <a class="navbar-brand text-light" href="#">Pesona NTT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-light" href="index.php"><i style='font-size:24px' class='fas'>&#xf015;</i> Beranda</a>
      </li>

    </ul>
  </div>  
</nav>
<br>
      <div class="row">
      <?php
      $objekwisata = buka($_GET['idobjekwisata']);
      $idbb = $_GET['idobjekwisata'];
      ?>
      <div class="col-sm-9">
      <div class="row">
        <div class="col-sm-3"><?php 
      //Display image
      $file = $objekwisata;
      if(file_exists("superadmin/berkas/$file.jpg")){
        ?><img class="zoom" src="superadmin/berkas/<?php echo $file ?>.jpg" width="100%" height="120" />
      <?php
      } else { ?>
        <center> <img class="zoom" src="superadmin/berkas/kosong.png" width="80" height="80" /> </center>
          <?php
      }
      ?>  </div>
  
        <div class="col-sm-9 tilt-in-right-1"> <?php
        //Mencari data di dalam database sesuai dengan inputan yang dimasukan
        $data1 = mysqli_query($konektor,"SELECT * from tbl_objekwisata, tbl_kategoriobjekwisata where tbl_kategoriobjekwisata.idkategori = tbl_objekwisata.idkategori and tbl_objekwisata.idobjekwisata like $objekwisata");
        if (mysqli_num_rows($data1)>0)
        { 
            while ($d1 = mysqli_fetch_array($data1)) {
            echo '<h3>' . $d1['nama'] .'</h3>'. $d1['deskripsi'];
            $judulobjekwisata = $d1['nama'];
          }
        }
      ?>
    
<div class="alert alert-light">
  <a href="whatsapp://send?text=informasi objek wisata <?php echo $judulobjekwisata; ?> . silahkan baca artikelnya dengancara mengklik tautan dibawa ini: http://ottudynno.my.id/displayObjek.php?idobjekwisata=<?php echo $idbb; ?> ">Bagikan ke WhatsApp</a>
</div>

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v9.0" nonce="DYXHLM0v"></script>
<div class="fb-like" data-href="http://ottudynno.my.id/displayObjek.php?idobjekwisata=<?php echo $idbb; ?>;" data-width="" data-layout="standard" data-action="like" data-size="small" data-share="true"></div>

	<!-- cek apakah sudah login -->
<!-- Cara 2 Jika halaman login menyatu dengan halaman index -->
	<?php 
	if($_SESSION['status'] =="login"){
    
    
   
    
    //Mencari data di dalam database sesuai dengan inputan yang dimasukan
    $data2 = mysqli_query($konektor,"SELECT * from tbl_wisatawan where telepon like '$_SESSION[username]'");
    if (mysqli_num_rows($data2)>0)
    { 
        while ($d2 = mysqli_fetch_array($data2)) {
        $idwisatawan = $d2['idwisatawan'];
      }
    }

  
    //insert form testimoni
    ?> <br>

	<?php 
	if(isset($_GET['pesan'])) {
		if($_GET['pesan'] == "simpantestimoni"){ ?>
    <div class="alert alert-success">
		<i style='font-size:14px' class='fas'>&#xf05a;</i>	Terimakasih Anda Telah Memberikan Testimoni . Testimoni Anda Akan Direview Terlebih Dahulu Sebelum Dipublikasi
    </div>
<?php  
    } else if ($_GET ['pesan'] =="ubahtestimoni") { ?>
      <div class="alert alert-success">
      <i style='font-size:14px' class='fas'>&#xf05a;</i> Terima kasih anda telah berhasil mengubah testimoni 
      </div>

   <?php  
    } else if ($_GET ['pesan'] =="hapustestimoni") { ?>
      <div class="alert alert-danger">
      <i style='font-size:14px' class='fas'>&#xf05a;</i> Terima kasih anda telah berhasil menghapus salah satu testimoni 
      </div>

	<?php	}
  }
  
	?>
      <form onsubmit="return confirm('Yakin ingin menyimpan data sekarang?');" method="post" action="inserttestimoni2.php">
         <!-- Input Text Field-->
         <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Judul Testimoni</span>
          </div>
            <input class="form-control" required type="text" name="judul"> 
        </div>
        
        <!-- Input Text Area-->
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Isi Testimoni</span>
          </div>
           <textarea class="form-control" required name="deskripsi"></textarea> 
           <input type="hidden" name="idobjekwisata" value="<?php echo buka($_GET['idobjekwisata']); ?>"> 
          <input type="hidden" name="idwisatawan" value="<?php echo $idwisatawan; ?>"> 
          <input type="hidden" name="tanggal" value="<?php echo date('Y-m-d'); ?>"> 
        </div> 
        
         <!-- Input Button-->
         <input class="btn btn-success" type="submit" value="Simpan">
         </form> 
        

    <?php


	} else {?>
    <div class="alert alert-danger"><i style='font-size:14px' class='fas'>&#xf05a;</i> Untuk Mengisi Testimoni Silahkan Kembali Ke Beranda Untuk Melakukan Login Terlebi Dahulu</div>
	<?php }
	?>
      
      </div>
      </div> 
      </div>
        <div class="col-sm-3">
        <?php
          //Mencari data di dalam database sesuai dengan inputan yang dimasukan
          $data = mysqli_query($konektor,"SELECT tbl_objekwisata.idobjekwisata, tbl_testimoni.idtestimoni, tbl_testimoni.tanggal, tbl_wisatawan.namawisatawan, tbl_wisatawan.idwisatawan, tbl_objekwisata.nama, tbl_testimoni.deskripsi FROM `tbl_testimoni`,tbl_wisatawan,tbl_objekwisata WHERE tbl_testimoni.idwisatawan = tbl_wisatawan.idwisatawan AND tbl_testimoni.idobjekwisata = tbl_objekwisata.idobjekwisata AND tbl_testimoni.status = '1' ORDER BY tbl_testimoni.idtestimoni DESC LIMIT 5");
          if (mysqli_num_rows($data)>0)
          { 
              while ($d = mysqli_fetch_array($data)) { ?>
           <div class="toast" data-autohide="false">
            <div class="toast-header">
               <strong class="mr-auto text-primary"><a style="text-decoration:none" href="displayObjek.php?idobjekwisata=<?php echo kunci($d['idobjekwisata']); ?>"><i style='font-size:20px' class='fas'>&#xf4d8;</i> <?php echo $d['nama']; ?></a></strong>
              <small class="text-muted"><?php echo $d['tanggal']; ?></small>
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
            </div>
            <div class="toast-body">
            <?php echo $d['namawisatawan']; ?> : <?php echo $d['deskripsi']; ?> 

            <?php
              if($idwisatawan == $d['idwisatawan']) {
                $ido = buka($_GET['idobjekwisata']);
                ?>
                  <a href="#"data-toggle="modal" data-target="#myModalubahtestimoni<?php echo $d['idtestimoni']; ?>"> <i style='font-size:14px' class='fas'>&#xf044;</i> </a>
                  <a onclick="return confirm('Yakin ingin menghapus data sekarang?');" href="delateTestimoni.php?idtestimoni=<?php echo kunci($d['idtestimoni']); ?>&idobjekwisata=<?php echo kunci($ido); ?>"><i style='font-size:14px' class='fas'>&#xf2ed;</i> </a>
                <?php
              }

            ?> 
            </div>
          </div>


        <script>
        $(document).ready(function(){
          $('.toast').toast('show');
        });
        </script> 

 <!-- The Modal Ubah Data Testimoni -->
 <div class="modal fade" id="myModalubahtestimoni<?php echo $d['idtestimoni']; ?>">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header"style="background-image: url(image/navbar2.jpg);background-size: cover;">
          <h4 class="modal-title text-light">Ubah Data Testimoni</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
        <div class="alert alert-info">
       <strong> <?php echo $d['nama']; ?> </strong>
        </div>
        <!--Form ubah data menyatu dengan form index-->
       <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="updatetestimoni.php">
        <!-- Edit Text Field-->
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Isi Testimoni</span>
          </div>
          <textarea class="form-control" required name="deskripsi"><?php echo $d['deskripsi']; ?></textarea>
          <input type="hidden" name="idtestimoni" value="<?php echo $d['idtestimoni']; ?>">
          <input type="hidden" name="idobjekwisata" value="<?php echo $d['idobjekwisata']; ?>">
        </div>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
               <!-- Input Button-->
          <input class="btn btn-success" type="submit" value="Simpan">
          </form>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
        </div>
      </div>
    </div>
  </div>


      <?php }
          }
      ?>
  
    </div>
  </div> 
  
</div>

</body>
</html>