<!DOCTYPE html>
<html lang="en">

<head>
  <title>Pesona NTT</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="shortcut icon" href="../image/icon.png">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <script type="text/javascript" src="chartjs294/Chart.js"></script>
  <style>
    .tilt-in-top-1 {
      -webkit-animation: tilt-in-top-1 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
      animation: tilt-in-top-1 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    .puff-in-tr {
      -webkit-animation: puff-in-tr 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
      animation: puff-in-tr 0.7s cubic-bezier(0.470, 0.000, 0.745, 0.715) both;
    }

    @-webkit-keyframes tilt-in-top-1 {
      0% {
        -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
        transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
        opacity: 0;
      }

      100% {
        -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
        transform: rotateY(0deg) translateY(0) skewY(0deg);
        opacity: 1;
      }
    }

    @keyframes tilt-in-top-1 {
      0% {
        -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
        transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
        opacity: 0;
      }

      100% {
        -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
        transform: rotateY(0deg) translateY(0) skewY(0deg);
        opacity: 1;
      }
    }

    /* ----------------------------------------------
 * Generated by Animista on 2020-11-21 5:24:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation puff-in-tr
 * ----------------------------------------
 */
    @-webkit-keyframes puff-in-tr {
      0% {
        -webkit-transform: scale(2);
        transform: scale(2);
        -webkit-transform-origin: 100% 0%;
        transform-origin: 100% 0%;
        -webkit-filter: blur(4px);
        filter: blur(4px);
        opacity: 0;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 100% 0%;
        transform-origin: 100% 0%;
        -webkit-filter: blur(0px);
        filter: blur(0px);
        opacity: 1;
      }
    }

    @keyframes puff-in-tr {
      0% {
        -webkit-transform: scale(2);
        transform: scale(2);
        -webkit-transform-origin: 100% 0%;
        transform-origin: 100% 0%;
        -webkit-filter: blur(4px);
        filter: blur(4px);
        opacity: 0;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: 100% 0%;
        transform-origin: 100% 0%;
        -webkit-filter: blur(0px);
        filter: blur(0px);
        opacity: 1;
      }
    }
  </style>
</head>

<body>

  <?php session_start();
  include 'konektor.php';
  error_reporting(0); ?>

  <nav class="navbar fixed-top navbar-expand-md bg-dark navbar-dark" style="background-image: url(../image/navbar2.jpg);background-size: cover;">
    <img src="../image/icon2.png" width="55px" height="35px">
    <a class="navbar-brand text-light" href="#">Pesona NTT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-light" href="#"><i style='font-size:14px' class='fas'>&#xf015;</i> Beranda</a>
        </li>

        <?php if ($_SESSION['status'] == "login") { ?>

          <li class="nav-item">
            <a class="nav-link text-light" href="#" data-toggle="modal" data-target="#mymodaladmin"><i style='font-size:14px' class='fas'>&#xf406;</i> Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#" data-toggle="modal" data-target="#mymodalkategori"><i style="font-size:14px" class="fa">&#xf03a;</i>
              Ketegori</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#" data-toggle="modal" data-target="#mymodalobjek"><i style='font-size:14px' class='fas'>&#xf5a0;</i> Objek Wisata <span class="badge badge-primary">
                <?php
                $datab1 = mysqli_query($konektor, "select count(idobjekwisata) as jumlah from tbl_objekwisata");
                if (mysqli_num_rows($datab1) > 0) {
                  while ($db1 = mysqli_fetch_array($datab1)) {
                    echo $db1['jumlah'];
                  }
                } //Data ditemukan dan ditampilkan ke layar
                else {
                  echo '0';
                }
                ?></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#" data-toggle="modal" data-target="#mymodalwisatawan"><i style='font-size:14px' class='fas'>&#xf0c0;</i> Wisatawan <span class="badge badge-primary">
                <?php
                $datab2 = mysqli_query($konektor, "select count(idwisatawan) as jumlah from tbl_wisatawan");
                if (mysqli_num_rows($datab2) > 0) {
                  while ($db2 = mysqli_fetch_array($datab2)) {
                    echo $db2['jumlah'];
                  }
                } //Data ditemukan dan ditampilkan ke layar
                else {
                  echo '0';
                }
                ?></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#" data-toggle="modal" data-target="#mymodaltestimoni"> <i style='font-size:14px' class='fas fa-comment-alt'></i> Testimoni <span class="badge badge-primary">
                <?php
                $datab3 = mysqli_query($konektor, "select count(idtestimoni) as jumlah from tbl_testimoni");
                if (mysqli_num_rows($datab3) > 0) {
                  while ($db3 = mysqli_fetch_array($datab3)) {
                    echo $db3['jumlah'];
                  }
                } //Data ditemukan dan ditampilkan ke layar
                else {
                  echo '0';
                }
                ?></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="logout.php"><i style='font-size:14px' class='fas'>&#xf2f5;</i> Logout</a>
          </li>
        <?php } ?>
      </ul>
    </div>
  </nav>
  <br>

  <div class="container">

    <!-- Cara 2 Jika halaman login menyatu dengan halaman index -->
    <?php
    include 'konektor.php';
    include 'enkripsivariabel.php';
    if ($_SESSION['status'] != "login") { ?>
      <br><br><br><br><br>
      <!-- belum login -->
      <div class="row">
        <div class="col-sm-4 mx-auto shadow p-3 mb-3 bg-white">

          <!-- Cek pesan notifikasi -->
          <?php
          if (isset($_GET['pesan'])) {
            if ($_GET['pesan'] == "gagal") { ?>
              <div class="alert alert-danger tilt-in-top-1"> <i style='font-size:20px' class='far'>&#xf119;</i>
                Login gagal! Username dan password salah!
              </div>
            <?php } else if ($_GET['pesan'] == "logout") { ?>
              <div class="alert alert-info tilt-in-top-1"> <i style='font-size:20px' class='fas'>&#xf05a;</i>
                Anda telah berhasil logout
              </div>
            <?php } else if ($_GET['pesan'] == "Belum_login") { ?>
              <div class="alert alert-warning tilt-in-top-1"> <i style='font-size:20px' class='far'>&#xf119;</i>
                Anda harus login untuk mengakses halaman super admin
              </div>
          <?php }
          }
          ?>
          <!-- form input Login !-->
          <form method="post" action="cekLogin.php">
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <span class="input-group-text">Username</span>
              </div>
              <input class="form-control" required type="text" name="username" placeholder="Masukkan Username">
            </div>

            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <span class="input-group-text">Password</span>
              </div>
              <input class="form-control" required type="password" name="sandi" placeholder="Masukkan Password">
            </div>
            <input class="btn btn-success" type="submit" value="Login"></td>
          </form>

        </div>
      </div>
      <!-- belum login selesai -->
      <!--notifikasi login -->
    <?php } else { ?><br><br><br><br><br>

      <div class="row">
        <div class="col-sm-6">
          <!-- kontel kolom 1-->

          <div class="row">
            <div class=col-sm-12>
              <div class="alert alert-success tilt-in-top-1"><i style='font-size:20px' class='far'>&#xf118;</i> <?php
                                                                                                                echo "Selamat Datang " . $_SESSION['username']; ?>
              </div>
            </div>
          </div>


          <?php
          if (isset($_GET['pesan'])) {
            if ($_GET['pesan'] == "tersimpan") { ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-info puff-in-tr "><i style='font-size:20px' class='fas'>&#xf05a;</i> <?php
                                                                                                                echo "Data baru telah disimpan";
                                                                                                                ?>
                  </div>
                </div>
              </div>


            <?php } else if ($_GET['pesan'] == "ubah") { ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-info puff-in-tr "><i style='font-size:20px' class='fas'>&#xf05a;</i> <?php
                                                                                                                echo "Data yang Anda pilih telah diubah"; ?>
                  </div>
                </div>
              </div>


            <?php } else if ($_GET['pesan'] == "hapus") { ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-info puff-in-tr "><i style='font-size:20px' class='fas'>&#xf05a;</i> <?php
                                                                                                                echo "Data yang Anda pilih telah dihapus";
                                                                                                                ?>
                  </div>
                </div>
              </div>

            <?php } else if ($_GET['pesan'] == "duplikat") { ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-danger puff-in-tr "><i style='font-size:20px' class='far'>&#xf119;</i> <?php
                                                                                                                  echo "Maaf tidak tersimpan karena terjadi duplikat Username . silahkan masukan username yang berbeda";
                                                                                                                  ?>
                  </div>
                </div>
              </div>


            <?php } else if ($_GET['pesan'] == "fileterkirim") {
              $name = buka($_GET['name']);
              $size = buka($_GET['size']);
              $type = buka($_GET['type']); ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-success puff-in-tr "><i style='font-size:20px' class='far'>&#xf118;</i> <?php

                                                                                                                  echo "File Berhasil Dikirim. Berikut Ini Informasinya : 
            <br>Nama File: $name
            <br>Ukuran File: $size
            <br>Tipe File: $type";
                                                                                                                  ?>
                  </div>
                </div>
              </div>
            <?php } else if ($_GET['pesan'] == "filegagalterkirim") {
              $name = buka($_GET['name']);
              $size = buka($_GET['size']);
              $type = buka($_GET['type']); ?>
              <div class="row">
                <div class=col-sm-12>
                  <div class="alert alert-danger puff-in-tr "><i style='font-size:20px' class='far'>&#xf119;</i> <?php
                                                                                                                  echo "File Gagal Dikirim. Berikut Ini Informasinya : 
          <br>Nama File: $name
          <br>Ukuran File: $size
          <br>Tipe File: $type";
                                                                                                                  ?>
                  </div>
                </div>
              </div>

          <?php }
          }
          ?>

          <!-- The Modal Dispal Data Admin-->
          <div class="modal fade" id="mymodaladmin">
            <div class="modal-dialog modal-xl">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header" style="background-color:#1fb4f4;">
                  <h4 class="modal-title text-light"><i style='font-size:24px' class='fas'>&#xf406;</i> Daftar Admin</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <a href="#" class="btn btn-info" data-toggle="modal" data-target="#myModalinsertadmin"><i style='font-size:14px' class='fas'>&#xf055;</i> Data</a>
                  <a href="report/LaporanAdminSeluruh.php" target="_blank" class="btn btn-danger"><i style='font-size:20px' class='far'>&#xf1c1;</i> </a>
                  <a href="excel/eadmin.php" class="btn btn-success"><i style='font-size:20px' class='far'>&#xf1c3;</i> </a>
                  <br><br>
                  <input class="form-control" id="myInputadmin" type="text" placeholder="Cari..">
                  <br>
                  <div class="table-responsive">
                    <table class="table table-striped table-hover table-sm" id="myTableadmin">
                      <thead>
                        <tr>
                          <th>ID Admin</th>
                          <th>Nama Admin</th>
                          <th>Alamat</th>
                          <th>Telepon</th>
                          <th>Email</th>
                          <th>Username</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_admin");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <tr>
                            <td><?php echo $d['idadmin']; ?></td>
                            <td><?php echo $d['nama']; ?></td>
                            <td><?php echo $d['alamat']; ?></td>
                            <td><?php echo $d['telepon']; ?></td>
                            <td><?php echo $d['email']; ?></td>
                            <td><?php echo $d['username']; ?></td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#myModalubahadmin<?php echo $d['idadmin']; ?>""><i style='font-size:14px' class='far'>&#xf044;</i> Ubah</a> 
                  <a onclick=" return confirm('Yakin ingin hapus data sekarang?');" href="delete/deleteadmin.php?id=<?php echo kunci($d['idadmin']); ?>"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                            </td>
                          </tr>

                          <!-- The Modal Ubah data admin-->
                          <div class="modal fade" id="myModalubahadmin<?php echo $d['idadmin']; ?>">
                            <div class="modal-dialog modal-lg">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Ubah Data Admin</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">

                                  <!-- Form ubah data menyatu dengan form index-->
                                  <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="edit/editadmin.php">
                                    <!-- Hiden fill idandin -->
                                    <input type="hidden" name="idadmin" value="<?php echo $d['idadmin']; ?>">
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Nama Admin</span>
                                      </div>
                                      <input type="text" class="form-control" required name="nama" value="<?php echo $d['nama']; ?>">
                                      </di>

                                      <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">Alamat</span>
                                        </div>
                                        <input type="text" class="form-control" required name="alamat" value="<?php echo $d['alamat']; ?>">
                                      </div>

                                      <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">Telepon</span>
                                        </div>
                                        <input type="number" class="form-control" required name="telepon" value="<?php echo $d['telepon']; ?>">
                                        </di>

                                        <div class="input-group mb-2">
                                          <div class="input-group-prepend">
                                            <span class="input-group-text">Email</span>
                                          </div>
                                          <input type="email" class="form-control" required name="email" value="<?php echo $d['email']; ?>">
                                          </di>

                                          <div class="input-group mb-2">
                                            <div class="input-group-prepend">
                                              <span class="input-group-text">User Name</span>
                                            </div>
                                            <input type="text" class="form-control" required name="username" value="<?php echo $d['username']; ?>">
                                            </di>

                                            <div class="input-group mb-2">
                                              <div class="input-group-prepend">
                                                <span class="input-group-text">Password</span>
                                              </div>
                                              <input type="password" class="form-control" required name="sandi" value="<?php echo $d['sandi']; ?>">
                                              </di>

                                              <!-- Input Button-->


                                              <!-- Akhir form ubah data -->
                                            </div>

                                            <!-- Modal footer -->
                                            <div class="modal-footer">
                                              <input class="btn btn-success" type="submit" value="Simpan">
                                  </form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>

                        <?php } ?>
                      </tbody>
                    </table>
                  </div>

                  <script>
                    $(document).ready(function() {
                      $("#myInputadmin").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTableadmin tr").filter(function() {
                          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                      });
                    });
                  </script>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Insert Data Admin-->
          <div class="modal fade" id="myModalinsertadmin">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title"> Tambah Data Admin</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <form method="post" action="insert/insertadmin.php">
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Nama Admin</span>
                      </div>
                      <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama">
                    </div>

                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Alamat</span>
                      </div>
                      <input type="text" class="form-control" required name="alamat">
                    </div>

                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Telepon</span>
                      </div>
                      <input type="number" class="form-control" required name="telepon">
                    </div>

                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Email</span>
                      </div>
                      <input type="email" class="form-control" required name="email">
                    </div>

                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Username</span>
                      </div>
                      <input type="text" class="form-control" required name="username">
                    </div>

                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Password</span>
                      </div>
                      <input type="password" class="form-control" required name="sandi">
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <input class="btn btn-success" type="submit" value="Simpan"> </form>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Kategori-->
          <div class="modal fade" id="mymodalkategori">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header" style="background-color:#1fb4f4;">
                  <h4 class="modal-title text-light"><i style="font-size:24px" class="fa">&#xf03a;</i> Daftar Kategori Objek Wisata</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <a href="#" class="btn btn-info" data-toggle="modal" data-target="#myModalinsertkategori"><i style='font-size:14px' class='fas'>&#xf055;</i> Data</a>
                  <a href="report/LaporanKategoriSeluruh.php" target="_blank" class="btn btn-danger"><i style='font-size:20px' class='far'>&#xf1c1;</i> </a>
                  <a href="excel/ekategori.php" class="btn btn-success"><i style='font-size:20px' class='far'>&#xf1c3;</i> </a>
                  <br><br>
                  <input class="form-control" id="myInputkategori" type="text" placeholder="Cari..">
                  <br>
                  <div class="table-responsive">
                    <table class="table table-striped table-hover table-sm" id="myTablekategori">
                      <thead>
                        <tr>
                          <th>ID Kategori</th>
                          <th>Nama Kategori</th>

                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_kategoriobjekwisata");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <tr>
                            <td><?php echo $d['idkategori']; ?></td>
                            <td><?php echo $d['namakategori']; ?></td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#myModalubahkategori<?php echo $d['idkategori']; ?>"><i style='font-size:14px' class='far'>&#xf044;</i> Ubah</a>

                              <?php
                              $data6 = mysqli_query($konektor, "select * from tbl_objekwisata where idkategori like '$d[idkategori]'");
                              if (mysqli_num_rows($data6) > 0) {
                                while ($d6 = mysqli_fetch_array($data6)) { //Data ditemukan 
                              ?>
                                  <a href="#" onclick="alert('Data yang Anda pilih tidak dapat dihapus karena sedang digunakan')"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                                <?php break;
                                }
                              } //Data tidak ditemukan
                              else { ?>
                                <a onclick="return confirm('Yakin ingin hapus data sekarang?');" href="delete/deletekategori.php?id=<?php echo kunci($d['idkategori']); ?>"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                              <?php }
                              ?>
                            </td>
                          </tr>

                          <!-- The Modal Ubah Data Kategori Wisata-->
                          <div class="modal fade" id="myModalubahkategori<?php echo $d['idkategori']; ?>">
                            <div class="modal-dialog modal-md">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Ubah Data Kategori</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <!-- Form ubah data menyatu dengan form index-->
                                  <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="edit/editkategori.php">
                                    <!-- Hiden fill idandin -->
                                    <input type="hidden" name="idkategori" value="<?php echo $d['idkategori']; ?>">
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Nama Kategori</span>
                                      </div>
                                      <input type="text" class="form-control" required name="namakategori" value="<?php echo $d['namakategori']; ?>">
                                    </div>

                                    <!-- Akhir form ubah data -->
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <input class="btn btn-success" type="submit" value="Simpan">
                                  </form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                        <?php } ?>
                      </tbody>
                    </table>
                  </div>

                  <script>
                    $(document).ready(function() {
                      $("#myInputkategori").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTablekategori tr").filter(function() {
                          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                      });
                    });
                  </script>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Insert Data Kategori-->
          <div class="modal fade" id="myModalinsertkategori">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Tambah Data Kategori</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">

                  <form method="post" action="insert/insertkategori.php">
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Nama Kategori</span>
                      </div>
                      <input type="text" class="form-control" required name="namakategori">
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <!-- Input Button-->
                  <input class="btn btn-success" type="submit" value="Simpan"></form>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>

          <!-- The Modal Objek Wisatawan-->
          <div class="modal fade" id="mymodalobjek">
            <div class="modal-dialog modal-xl">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header" style="background-color:#1fb4f4;">
                  <h4 class="modal-title text-light"><i style='font-size:24px' class='fas'>&#xf5a0;</i> Dafatr Objek Wisata</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <a href="#" class="btn btn-info" data-toggle="modal" data-target="#myModalinsertwisata"><i style='font-size:14px' class='fas'>&#xf055;</i> Data</a>
                  <a href="report/LaporanObjekwisatawanSeluruh.php" target="_blank" class="btn btn-danger"><i style='font-size:20px' class='far'>&#xf1c1;</i> Laporan </a>
                  <a href="excel/eobjek.php" class="btn btn-success"><i style='font-size:20px' class='far'>&#xf1c3;</i> </a>
                  <br><br>
                  <input class="form-control" id="myInputobjek" type="text" placeholder="Cari..">
                  <br>
                  <!-- Awal Progres Bar -->
                  <?php
                  //menghitung total rcord objek wisata
                  $datarow1 = mysqli_query($konektor, "SELECT count(idobjekwisata) AS total FROM tbl_objekwisata");
                  if (mysqli_num_rows($datarow1) > 0) {
                    while ($drow1 = mysqli_fetch_array($datarow1)) {
                      $total = $drow1['total'];
                    }
                  } else {
                    $total = 0;
                  }


                  //menghitung total rcord objek wisata menurut publish

                  $datarow2 = mysqli_query($konektor, "SELECT count(idobjekwisata) AS totalp FROM tbl_objekwisata WHERE status = '1'");
                  if (mysqli_num_rows($datarow2) > 0) {
                    while ($drow2 = mysqli_fetch_array($datarow2)) {
                      $totalp = $drow2['totalp'];
                    }
                  } else {
                    $totalp = 0;
                  }


                  //menghitung total rcord objek wisata menurut tunda

                  $datarow3 = mysqli_query($konektor, "SELECT count(idobjekwisata) AS totalt FROM tbl_objekwisata WHERE status = '0'");
                  if (mysqli_num_rows($datarow3) > 0) {
                    while ($drow3 = mysqli_fetch_array($datarow3)) {
                      $totalt = $drow3['totalt'];
                    }
                  } else {
                    $totalt = 0;
                  }
                  ?>
                  <div class="progress" style="height:30px">
                    <div class="progress-bar  progress-bar-striped progress-bar-animated" style="width:<?php echo round(($totalp / $total) * 100, 0); ?>%;background-color: #1fb4f4;">
                      Publish <?php echo round(($totalp / $total) * 100, 0); ?>%
                    </div>
                    <div class="progress-bar  progress-bar-striped progress-bar-animated" style="width:<?php echo round(($totalt / $total) * 100, 0); ?>%;background-color: #42f9bc;">
                      Tunda <?php echo round(($totalt / $total) * 100, 0); ?>%
                    </div>
                  </div>
                  <!-- ahkir progres Bar -->
                  <br>
                  <div class="table-responsive">
                    <table class="table table-striped table-hover table-sm" id="myTableobjek">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Nama</th>
                          <th>Kategori</th>
                          <th>Deskripsi</th>
                          <th>Alamat</th>
                          <th>Status</th>
                          <th>Gambar</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $data = mysqli_query($konektor, "SELECT tbl_objekwisata.`idobjekwisata`,tbl_objekwisata.nama, tbl_objekwisata.status, tbl_kategoriobjekwisata.namakategori, tbl_kategoriobjekwisata.idkategori, tbl_objekwisata.deskripsi,tbl_objekwisata.alamat, if (tbl_objekwisata.status = '1', 'publish','tunda') AS publikasi FROM `tbl_objekwisata`, tbl_kategoriobjekwisata WHERE tbl_objekwisata.idkategori = tbl_kategoriobjekwisata.idkategori ");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <tr>
                            <td><?php echo $d['idobjekwisata']; ?></td>
                            <td><?php echo $d['nama']; ?></td>
                            <td><?php echo $d['namakategori']; ?></td>
                            <td><?php echo $d['deskripsi']; ?></td>
                            <td><?php echo $d['alamat']; ?></td>
                            <td><?php echo $d['publikasi']; ?></td>
                            <td>
                              <center>
                                <?php
                                //Display image
                                $file = $d['idobjekwisata'];
                                if (file_exists("berkas/$file.jpg")) {
                                ?><a href="berkas/<?php echo $d['idobjekwisata']; ?>.jpg" target="_blank"><img class="tilt-in-top-1" src="berkas/<?php echo $d['idobjekwisata']; ?>.jpg" width="80" height="80" />
                                  <?php
                                } else { ?>
                                    <img src="berkas/kosong.png" width="80" height="80" />
                                  <?php
                                }
                                  ?>
                                  <br>
                                  <a href="#" data-toggle="modal" data-target="#myModalunggahgambar<?php echo $d['idobjekwisata']; ?>"><i style='font-size:14px' class='fas'>&#xf093;</i></a>
                            </td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#myModalubahobjek<?php echo $d['idobjekwisata']; ?>"><i style='font-size:14px' class='far'>&#xf044;</i> Ubah</a>
                              <a onclick="return confirm('Yakin ingin hapus data sekarang?');" href="delete/deleteobjekwisata.php?id=<?php echo kunci($d['idobjekwisata']); ?>"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                              <center>
                            </td>
                          </tr>

                          <!-- The Modal unggah gambar-->
                          <div class="modal fade" id="myModalunggahgambar<?php echo $d['idobjekwisata']; ?>">
                            <div class="modal-dialog modal-sm">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Unggah Gambar</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  File yang anda kirim tidak boleh lebih daro 10MB . <br> <br>Anda Akan Mengunggah Gambar Untuk Objek Wisata <strong><?php echo $d['nama']; ?></strong>
                                  <form action="unggahAksi.php" method="post" enctype="multipart/form-data">
                                    <input type="hidden" name="id" value="<?php echo $d['idobjekwisata']; ?>"> <!-- Untuk penamaan file -->
                                    <input type="file" class="form-control" name="berkas">

                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <button class="btn btn-info" type="submit">Unggah</button></form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>

                          <!-- The Modal ubah data objek wisata -->
                          <div class="modal fade" id="myModalubahobjek<?php echo $d['idobjekwisata']; ?>">
                            <div class="modal-dialog modal-md">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Ubah Data Objek Wisata</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">

                                  <!-- Form ubah data menyatu dengan form index-->
                                  <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="edit/editobjekwisata.php">
                                    <!-- Hiden fill idkategori -->
                                    <input type="hidden" name="idobjekwisata" value="<?php echo $d['idobjekwisata']; ?>">
                                    <!-- Edit List Menu Dinamis-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Kategori</span>
                                      </div>
                                      <?php
                                      $data1 = mysqli_query($konektor, "select * from tbl_kategoriobjekwisata");
                                      echo "<select class='form-control' required name='idkategori'>";
                                      // Mengambil value dari tabel dan disimpan pada variabel $existingid
                                      $existingid = $d['idkategori'];
                                      while ($d1 = mysqli_fetch_array($data1)) {
                                        // cek jika $existingid sama dengan yang dipilih untuk ditampilkan
                                        if ($existingid == $d1['idkategori'])
                                          echo "<option selected='selected' value='" . $d1['idkategori'] . "'>" . $d1['namakategori'] . "</option>";
                                        else
                                          echo "<option value='" . $d1['idkategori'] . "'>" . $d1['namakategori'] . "</option>";
                                      }
                                      echo "</select>";
                                      ?>
                                    </div>

                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Nama Objek Wisata</span>
                                      </div>
                                      <input class="form-control" required type="text" name="nama" value="<?php echo $d['nama']; ?>">
                                    </div>

                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Deskripsi</span>
                                      </div>
                                      <input class="form-control" required type="text" name="deskripsi" value="<?php echo $d['deskripsi']; ?>">
                                    </div>

                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Alamat</span>
                                      </div>
                                      <input class="form-control" required type="text" name="alamat" value="<?php echo $d['alamat']; ?>">
                                    </div>

                                    <!-- Edit radio group status-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Status</span>
                                      </div> &nbsp;&nbsp;
                                      <label><input type="radio" name="status" value="1" <?php if ($d['status'] == '1') echo 'checked' ?>> Publish</label>
                                      &nbsp;&nbsp;<label><input type="radio" name="status" value="0" <?php if ($d['status'] == '0') echo 'checked' ?>> Tunda</label>
                                    </div>

                                    <!-- Akhir form ubah data -->
                                </div>

                                <!-- Modal footer -->
                                <!-- Input Button-->
                                <div class="modal-footer">
                                  <input class="btn btn-success" type="submit" value="Simpan">
                                  </form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                        <?php } ?>
                      </tbody>
                    </table>
                  </div>

                  <script>
                    $(document).ready(function() {
                      $("#myInputobjek").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTableobjek tr").filter(function() {
                          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                      });
                    });
                  </script>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Insert Objek Wisata-->
          <div class="modal fade" id="myModalinsertwisata">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title"> Tambah Data Objek Wisata</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <form method="post" action="insert/insertobjekwisata.php">


                    <!-- Input List Menu Dinamis-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Kategori</span>
                      </div>
                      <select name="idkategori" class="custom-select form-control" required>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_kategoriobjekwisata");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <option value="<?php echo $d['idkategori']; ?>"><?php echo $d['namakategori']; ?></option>
                        <?php } ?>
                      </select>
                    </div>

                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Nama Objek Wisata</span>
                      </div>
                      <input class="form-control" required type="text" name="nama">
                    </div>
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Deskripsi</span>
                      </div>
                      <input class="form-control" required type="text" name="deskripsi">
                    </div>
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Alamat</span>
                      </div>
                      <input class="form-control" required type="text" name="alamat">
                    </div>
                    <!-- Input List Menu Dinamis-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Status</span>
                      </div>
                      <select name="status" class="custom-select form-control" required>
                        <option value="1">Publish</option>
                        <option value="0">Tunda</option>
                      </select>
                    </div>

                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <!-- Input Button-->
                  <input class="btn btn-success" type="submit" value="Simpan"></form>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>

          <!-- The Modal Wisatawan-->
          <div class="modal fade" id="mymodalwisatawan">
            <div class="modal-dialog modal-xl">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header" style="background-color:#1fb4f4;">
                  <h4 class="modal-title text-light">
                    <i style='font-size:24px' class='fas'>&#xf0c0;</i> Daftar Wisatawan
                  </h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <a href="#" class="btn btn-info" data-toggle="modal" data-target="#myModalinsertwisatawam"><i style='font-size:14px' class='fas'>&#xf055;</i> Data</a>
                  <a href="report/LaporanWisatawanSeluruh.php" target="_blank" class="btn btn-danger"><i style='font-size:20px' class='far'>&#xf1c1;</i> </a>
                  <a href="excel/ewisatawan.php" class="btn btn-success"><i style='font-size:20px' class='far'>&#xf1c3;</i> </a>
                  <br><br>
                  <input class="form-control" id="myInputwisatawan" type="text" placeholder="Cari..">
                  <br>
                  <div class="table-responsive">
                    <table class="table table-striped table-hover table-sm" id="myTablewisatawan">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Nama Wisatawan</th>
                          <th>Telepon</th>
                          <th>Email</th>
                          <th>Jenis Kelamin</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_wisatawan");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <tr>
                            <td><?php echo $d['idwisatawan']; ?></td>
                            <td><?php echo $d['namawisatawan']; ?></td>
                            <td><?php echo $d['telepon']; ?></td>
                            <td><?php echo $d['email']; ?></td>
                            <td><?php echo $d['jenis_kelamin']; ?></td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#myModalubahwisatawan<?php echo $d['idwisatawan']; ?>"><i style='font-size:14px' class='far'>&#xf044;</i> Ubah</a>

                              <?php
                              $data7 = mysqli_query($konektor, "select * from tbl_testimoni where idwisatawan like '$d[idwisatawan]'");
                              if (mysqli_num_rows($data7) > 0) {
                                while ($d7 = mysqli_fetch_array($data7)) { //Data ditemukan 
                              ?>
                                  <a href="#" onclick="alert('Data yang Anda pilih tidak dapat dihapus karena sedang digunakan')"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                                <?php break;
                                }
                              } //Data tidak ditemukan
                              else { ?>
                                <a onclick="return confirm('Yakin ingin hapus data sekarang?');" href="delete/deletewisatawan.php?id=<?php echo kunci($d['idwisatawan']); ?>"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                              <?php }
                              ?>
                            </td>
                          </tr>
                          <!-- The Modal Ubah Data Wisata-->
                          <div class="modal fade" id="myModalubahwisatawan<?php echo $d['idwisatawan']; ?>">
                            <div class="modal-dialog modal-lg">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Ubah Data Wisatawan</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <!-- Form ubah data menyatu dengan form index-->
                                  <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="edit/editwisatawan.php">
                                    <!-- Hiden fill idkategori -->
                                    <input type="hidden" name="idwisatawan" value="<?php echo $d['idwisatawan']; ?>">
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Nama Wisatawan</span>
                                      </div>
                                      <input type="text" class="form-control" required name="namawisatawan" value="<?php echo $d['namawisatawan']; ?>">
                                    </div>
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Telepon</span>
                                      </div>
                                      <input type="number" class="form-control" required name="telepon" value="<?php echo $d['telepon']; ?>">
                                    </div>
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Email</span>
                                      </div>
                                      <input type="email" class="form-control" required name="email" value="<?php echo $d['email']; ?>">
                                    </div>
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Password</span>
                                      </div>
                                      <input type="password" class="form-control" required name="sandi" value="<?php echo $d['sandi']; ?>">
                                    </div>

                                    <!-- Edit radio group jenis kelamin-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Jenis Kelamin</span>
                                      </div> &nbsp;&nbsp;
                                      <label><input type="radio" name="jenis_kelamin" value="Laki-Laki" <?php if ($d['jenis_kelamin'] == 'Laki-Laki') echo 'checked' ?>>Laki-Laki</label>
                                      &nbsp;&nbsp;<label><input type="radio" name="jenis_kelamin" value="Perempuan" <?php if ($d['jenis_kelamin'] == 'Perempuan') echo 'checked' ?>>Perempuan</label>
                                    </div>

                                    <!-- Akhir form ubah data -->
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <!-- Input Button-->
                                  <input class="btn btn-success" type="submit" value="Simpan">
                                  </form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                        <?php } ?>
                      </tbody>
                    </table>
                  </div>

                  <script>
                    $(document).ready(function() {
                      $("#myInputwisatawan").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTablewisatawan tr").filter(function() {
                          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                      });
                    });
                  </script>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Insert WIsatawan -->
          <div class="modal fade" id="myModalinsertwisatawam">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Tambah Data Wisatawan</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <form method="post" action="insert/insertwisatawan.php">
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Nama Wisatawan</span>
                      </div>
                      <input pattern="[A-Za-z ]+" class="form-control" required type="text" name="namawisatawan">
                    </div>
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Telepon</span>
                      </div>
                      <input class="form-control" required type="number" name="telepon">
                    </div>
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Email</span>
                      </div>
                      <input class="form-control" required type="email" name="email">
                    </div>
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Password</span>
                      </div>
                      <input class="form-control" required type="password" name="sandi">
                    </div>

                    <!-- Input radio Group-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Jenis Kelamin</span>
                      </div> &nbsp;&nbsp;
                      <div class="custom-control  custom-radio custom-control-inline">
                        <input required type="radio" class="custom-control-input" id="customRadio" name="jenis_kelamin" value="LakiLaki">
                        <label class="custom-control-label" for="customRadio">Laki - Laki</label>
                      </div>
                      <div class="custom-control custom-radio custom-control-inline">
                        <input required type="radio" class="custom-control-input" id="customRadio2" name="jenis_kelamin" value="Perempuan">
                        <label class="custom-control-label" for="customRadio2">Perempuan</label>
                      </div>
                    </div>

                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <!-- Input Button-->
                  <input class="btn btn-success" type="submit" value="Simpan"></form>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>

          <!-- The Modal Testimoni-->
          <div class="modal fade" id="mymodaltestimoni">
            <div class="modal-dialog modal-xl">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header" style="background-color:#1fb4f4;">
                  <h4 class="modal-title text-light"><i style='font-size:24px' class='fas fa-comment-alt'></i> Daftar Testimoni</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <div class="row">
                    <div class="col-sm-1"><a href="#" class="btn btn-info" data-toggle="modal" data-target="#myModalinserttestimoni"><i style='font-size:14px' class='fas'>&#xf055;</i> Data</a></div>
                    <div class="col-sm-1">
                      <div class="dropdown">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i style='font-size:20px' class='far'>&#xf1c1;</i> </button>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" target="_blank" href="report/LaporanTestimoniSeluruh.php"><i style='font-size:14px' class='far'>&#xf15c;</i> Seluruh</a>
                          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#myModalfiltermenurutobjekwisata"><i style='font-size:14px' class='far'>&#xf15c;</i> Menurut Objek Wisata</a>
                          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#myModalfiltermenurutperiode"><i style='font-size:14px' class='far'>&#xf15c;</i> Menurut Periode</a>
                          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#myModalfiltermenurutperiode2"><i style='font-size:14px' class='far'>&#xf15c;</i> Menurut Periode & Objek Wisata</a>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-1"><a href="excel/etestimoni.php" class="btn btn-success"><i style='font-size:20px' class='far'>&#xf1c3;</i> </a></div>
                  </div>
                  <br>
                  <input class="form-control" id="myInputtestimoni" type="text" placeholder="Cari..">
                  <br>
                  <div class="table-responsive">
                    <table class="table table-striped table-hover table-sm" id="myTabletestimoni">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Tanggal</th>
                          <th>Nama Wisatawan</th>
                          <th>Objek</th>
                          <th>Judul</th>
                          <th>Isi</th>
                          <th>Status</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $data = mysqli_query($konektor, "SELECT tbl_testimoni.idtestimoni, tbl_testimoni.idwisatawan, tbl_testimoni.idobjekwisata, tbl_testimoni.status, tbl_testimoni.tanggal, tbl_wisatawan.namawisatawan, tbl_objekwisata.nama,tbl_testimoni.judul,tbl_testimoni.deskripsi, if (tbl_testimoni.status = '1','publish', 'tunda') AS publish FROM `tbl_testimoni`,tbl_wisatawan,tbl_objekwisata WHERE tbl_testimoni.idwisatawan = tbl_wisatawan.idwisatawan AND tbl_testimoni.idobjekwisata = tbl_objekwisata.idobjekwisata ");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <tr>
                            <td><?php echo $d['idtestimoni']; ?></td>
                            <td><?php echo $d['tanggal']; ?></td>
                            <td><?php echo $d['namawisatawan']; ?></td>
                            <td><?php echo $d['nama']; ?></td>
                            <td><?php echo $d['judul']; ?></td>
                            <td><?php echo $d['deskripsi']; ?></td>
                            <td><?php echo $d['publish']; ?></td>
                            <td>
                              <a href="#" data-toggle="modal" data-target="#myModalubahtestimoni<?php echo $d['idtestimoni']; ?>"><i style='font-size:14px' class='far'>&#xf044;</i> Ubah</a>
                              <a onclick="return confirm('Yakin ingin hapus data sekarang?');" href="delete/deletetestimoni.php?id=<?php echo kunci($d['idtestimoni']); ?>"><i style='font-size:14px' class='far'>&#xf2ed;</i> Hapus</a>
                            </td>
                          </tr>
                          <!-- The Modal Menurut Periode dan Objek Wisata-->
                          <div class="modal fade" id="myModalfiltermenurutperiode2">
                            <div class="modal-dialog modal-md">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Menurut Periode & Objek Wisata</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <form method="post" target="_blank" action="report/LaporanTestimoniGabung.php">
                                    <!-- Input Text Field Tanggal Mulai-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Mulai</span>
                                      </div>
                                      <input type="date" class="form-control" required name="tanggalmulai">
                                    </div>
                                    <!-- Input Text Field tanggal selesai-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Selesai</span>
                                      </div>
                                      <input class="form-control" required type="date" name="tanggalselesai">
                                    </div>

                                    <!-- Input List Menu Dinamis Objek wisata-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Objek Wisata</span>
                                      </div>
                                      <select name="idobjekwisata" class="custom-select form-control" required>
                                        <?php
                                        $data6 = mysqli_query($konektor, "select * from tbl_objekwisata");
                                        while ($d6 = mysqli_fetch_array($data6)) {
                                        ?>
                                          <option value="<?php echo $d6['idobjekwisata']; ?>"><?php echo $d6['nama']; ?></option>
                                        <?php } ?>
                                      </select>
                                    </div>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <!-- Input Button-->
                                  <input class="btn btn-success" type="submit" value="filter"></form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>

                          <!-- The Modal Filter Menurut Objek Wisata-->
                          <div class="modal fade" id="myModalfiltermenurutobjekwisata">
                            <div class="modal-dialog modal-md">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Menurut Objek Wisata</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <form method="post" target="_blank" action="report/Laporantestimonimenurutobjek.php">
                                    <!-- Input List Menu Dinamis-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Objek Wisata</span>
                                      </div>
                                      <select name="idobjekwisata" class="custom-select form-control" required>
                                        <?php
                                        $datadynno = mysqli_query($konektor, "select * from tbl_objekwisata");
                                        while ($ddynno = mysqli_fetch_array($datadynno)) {
                                        ?>
                                          <option value="<?php echo $ddynno['idobjekwisata']; ?>"><?php echo $ddynno['nama']; ?></option>
                                        <?php } ?>
                                      </select>
                                    </div>
                                </div>
                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <!-- Input Button-->
                                  <input class="btn btn-success" type="submit" value="Filter"></form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!-- The Modal Filter Menurutv Periode-->
                          <div class="modal fade" id="myModalfiltermenurutperiode">
                            <div class="modal-dialog modal-md">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Menurut Periode</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <form method="post" action="report/LaporanTestimoniperiode.php">
                                    <!-- Input Text Field Tanggal Mulai-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Mulai</span>
                                      </div>
                                      <input type="date" class="form-control" required name="tanggalmulai">
                                    </div>
                                    <!-- Input Text Field Tanggal Selesai-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Selesai</span>
                                      </div>
                                      <input class="form-control" required type="date" name="tanggalselesai">
                                    </div>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <!-- Input Button-->
                                  <input class="btn btn-success" type="submit" value="Filter"></form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!-- The Modal Ubah Data Testimoni -->
                          <div class="modal fade" id="myModalubahtestimoni<?php echo $d['idtestimoni']; ?>">
                            <div class="modal-dialog modal-lg">
                              <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                  <h4 class="modal-title">Ubah Data Testimoni</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                  <!-- Form ubah data menyatu dengan form index-->
                                  <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="edit/edittestimoni.php">
                                    <!-- Hiden fill idandin -->
                                    <input type="hidden" name="idtestimoni" value="<?php echo $d['idtestimoni']; ?>">
                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Tanggal</span>
                                      </div>
                                      <input type="date" class="form-control" required name="tanggal" value="<?php echo $d['tanggal']; ?>">
                                    </div>

                                    <!-- Edit List Menu Dinamis Wisatawan-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Wisatawan</span>
                                      </div>
                                      <?php
                                      $data1 = mysqli_query($konektor, "select * from tbl_wisatawan");
                                      echo "<select class='form-control' required name='idwisatawan'>";
                                      // Mengambil value dari tabel dan disimpan pada variabel $existingid
                                      $existingid = $d['idwisatawan'];
                                      while ($d1 = mysqli_fetch_array($data1)) {
                                        // cek jika $existingid sama dengan yang dipilih untuk ditampilkan
                                        if ($existingid == $d1['idwisatawan'])
                                          echo "<option selected='selected' value='" . $d1['idwisatawan'] . "'>" . $d1['namawisatawan'] . "</option>";
                                        else
                                          echo "<option value='" . $d1['idwisatawan'] . "'>" . $d1['namawisatawan'] . "</option>";
                                      }
                                      echo "</select>";
                                      ?>
                                    </div>

                                    <!-- Edit List Menu Dinamis Objek Wisataw-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Objek Wisata</span>
                                      </div>
                                      <?php
                                      $data1 = mysqli_query($konektor, "select * from tbl_objekwisata");
                                      echo "<select class='form-control' required name='idobjekwisata'>";
                                      // Mengambil value dari tabel dan disimpan pada variabel $existingid
                                      $existingid = $d['idobjekwisata'];
                                      while ($d1 = mysqli_fetch_array($data1)) {
                                        // cek jika $existingid sama dengan yang dipilih untuk ditampilkan
                                        if ($existingid == $d1['idobjekwisata'])
                                          echo "<option selected='selected' value='" . $d1['idobjekwisata'] . "'>" . $d1['nama'] . "</option>";
                                        else
                                          echo "<option value='" . $d1['idobjekwisata'] . "'>" . $d1['nama'] . "</option>";
                                      }
                                      echo "</select>";
                                      ?>
                                    </div>

                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Judul Testimoni</span>
                                      </div>
                                      <input class="form-control" required type="text" name="judul" value="<?php echo $d['judul']; ?>">
                                    </div>

                                    <!-- Edit Text Field-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Ulasan</span>
                                      </div>
                                      <input class="form-control" required type="text" name="deskripsi" value="<?php echo $d['deskripsi']; ?>">
                                    </div>

                                    <!-- Edit radio group status-->
                                    <div class="input-group mb-2">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text">Status</span>
                                      </div> &nbsp;&nbsp;
                                      <label><input type="radio" name="status" value="1" <?php if ($d['status'] == '1') echo 'checked' ?>> Publish</label>
                                      &nbsp;&nbsp;<label><input type="radio" name="0" value="tunda" <?php if ($d['status'] == '0') echo 'checked' ?>> Tunda</label>
                                    </div>
                                    <!-- Akhir form ubah data -->
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                  <!-- Input Button-->
                                  <input class="btn btn-success" type="submit" value="Simpan">
                                  </form>
                                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                                </div>
                              </div>
                            </div>
                          </div>
                        <?php } ?>
                      </tbody>
                    </table>
                  </div>

                  <script>
                    $(document).ready(function() {
                      $("#myInputtestimoni").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTabletestimoni tr").filter(function() {
                          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                      });
                    });
                  </script>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>


          <!-- The Modal Insert Testimoni-->
          <div class="modal fade" id="myModalinserttestimoni">
            <div class="modal-dialog modal-md">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Tambah Data Testimoni</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  <form method="post" action="insert/inserttestimoni.php">
                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Tanggal</span>
                      </div>
                      <input type="date" class="form-control" required name="tanggal">
                    </div>

                    <!-- Input List Menu Dinamis-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Wisatawan</span>
                      </div>
                      <select name="idwisatawan" class="custom-select form-control" required>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_wisatawan");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <option value="<?php echo $d['idwisatawan']; ?>"><?php echo $d['namawisatawan']; ?></option>
                        <?php } ?>
                      </select>
                    </div>

                    <!-- Input List Menu Dinamis-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Objek Wisata</span>
                      </div>
                      <select name="idobjekwisata" class="custom-select form-control" required>
                        <?php
                        $data = mysqli_query($konektor, "select * from tbl_objekwisata");
                        while ($d = mysqli_fetch_array($data)) {
                        ?>
                          <option value="<?php echo $d['idobjekwisata']; ?>"><?php echo $d['nama']; ?></option>
                        <?php } ?>
                      </select>
                    </div>

                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Judul</span>
                      </div>
                      <input class="form-control" required type="text" name="judul">
                    </div>

                    <!-- Input Text Field-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Deskripsi</span>
                      </div>
                      <input class="form-control" required type="text" name="deskripsi">
                    </div>

                    <!-- Input List Menu Dinamis-->
                    <div class="input-group mb-2">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Status</span>
                      </div>
                      <select name="status" class="custom-select form-control" required>
                        <option value="1">Publish</option>
                        <option value="0">Tunda</option>
                      </select>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <!-- Input Button-->
                  <input class="btn btn-success" type="submit" value="Simpan"> </form>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                </div>
              </div>
            </div>
          </div>

          <!--Konten kolom 2-->
        </div>
        <div class="col-sm-6">

          <!--Mulai grafik-->
          <center>
            <h6 class="tilt-in-top-1">GRAFIK STATUS PUBLIKASI KONTEN OBJEK WISATA</h6>
          </center>
          <div style="width: 100%;margin: 0px auto;">
            <canvas id="myChart"></canvas>
          </div>
          <script>
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
              type: 'pie', //bar: batang, pie: lingkaran, line: garis, 
              data: {
                labels: ["publish", "tunda"],
                datasets: [{
                  label: '',
                  data: [
                    <?php
                    $jumlah_data_1 = mysqli_query($konektor, "SELECT * from tbl_objekwisata where status='1'");
                    echo mysqli_num_rows($jumlah_data_1); //Menghitung jumlah record kolom 1
                    ?>,
                    <?php
                    $jumlah_data_2 = mysqli_query($konektor, "SELECT * from tbl_objekwisata where status='0'");
                    echo mysqli_num_rows($jumlah_data_2); //Menghitung jumlah record kolom 2
                    ?>
                  ],
                  //R: red, G: Green, B: Blue, A: Alpha (Mengatur transparansi warna)
                  backgroundColor: [
                    'rgba(243, 243, 1, 0.2)', //Warna isi grafik kolom 1
                    'rgba(4, 212, 51, 0.2)' //Warna isi grafik kolom 2
                  ],
                  borderColor: [
                    //R: red, G: Green, B: Blue, A: Alpha (Mengatur transparansi warna)
                    'rgba(243, 243, 1, 1)', //Warna border grafik kolom 1
                    'rgba(4, 212, 51, 1)' //Warna border grafik kolom 2
                  ],
                  borderWidth: 1
                }]
              },
              options: {
                scales: {
                  yAxes: [{
                    ticks: {
                      beginAtZero: true
                    }
                  }]
                }
              }
            });
          </script>
          <!--Selesai grafik-->
        </div>
      </div>
    <?php } ?>




  </div>
</body>

</html>